# Generated by Django 5.2.8 on 2025-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemberRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("room", models.PositiveIntegerField(blank=True, null=True)),
                ("buttons", models.JSONField(default=[1, 1, 1, 1, 1, 1])),
                ("audio1", models.BinaryField(blank=True, null=True)),
                ("audio2", models.BinaryField(blank=True, null=True)),
                ("audio3", models.BinaryField(blank=True, null=True)),
                ("is_owner", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Member Record",
                "verbose_name_plural": "Member Records",
                "db_table": "member_record",
            },
        ),
    ]
